// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0UVrC_Ib-96evDR2iGe4sh_OYF4LDas',
    appId: '1:605736709105:web:06029f3e6a45ab8763b250',
    messagingSenderId: '605736709105',
    projectId: 'fantasy-07',
    authDomain: 'fantasy-07.firebaseapp.com',
    storageBucket: 'fantasy-07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExuYYaCdJA0yJUMKb8ZLCwAohlqBhBAc',
    appId: '1:605736709105:android:c7b6698642d2604563b250',
    messagingSenderId: '605736709105',
    projectId: 'fantasy-07',
    storageBucket: 'fantasy-07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdkuZN8e_EtcIwDjOxij-78fUKrf4w7g',
    appId: '1:605736709105:ios:14fa2ce15eb4dc7363b250',
    messagingSenderId: '605736709105',
    projectId: 'fantasy-07',
    storageBucket: 'fantasy-07.appspot.com',
    iosBundleId: 'com.example.fantasy07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdkuZN8e_EtcIwDjOxij-78fUKrf4w7g',
    appId: '1:605736709105:ios:8f56286fc0c4e2e463b250',
    messagingSenderId: '605736709105',
    projectId: 'fantasy-07',
    storageBucket: 'fantasy-07.appspot.com',
    iosBundleId: 'com.example.fantasy07.RunnerTests',
  );
}
